### ISSUE TITLE
Request: Add License to prisma-extension-cache-manager

### ISSUE THREAD

**Issue by yxx4c** [random42/prisma-extension-cache-manager#1]
Hey random42,

I've noticed **prisma-extension-cache-manager**  doesn't have a license. Adding one would provide clarity on usage terms and encourage contributions. I suggest considering the MIT License for simplicity. Let's enhance collaboration!

Thanks,
yxx4c

**Comment by random42** [comment]
Yeah no problem, I'll add a MIT license
